version: "3"

services:
  strafforts:
    build: .
    image: dmintz7/strafforts
    container_name: strafforts
    environment:
      - SECRET_KEY_BASE=A000000000A #MUST CONTAIN ALPHA
      - STRAVA_API_CLIENT_ID=
      - STRAVA_API_CLIENT_SECRET=
      - DB_ENGINE=mysql2 #Use mysql2 for mysql and postgresql for PostgreSQL Database
      - DB_ENCODE=utf8 #Use utf8 for mysql and unicode for PostgreSQL
      - DB_NAME=strafforts  
      - DB_USER=
      - DB_PASS=
      - DB_HOST=
      - DB_PORT=3306
    ports:
      - "8100:5000"
